# Generated by Django 6.0.3 on 2026-04-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
